---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: galaxy-landing-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: galaxy-landing
  source:
    repoURL: http://gitlab.galaxy.dev/devops/argocd.git
    targetRevision: HEAD
    path: argocd-apps/galaxy-landing
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions: 
    - CreateNamespace=true
