{{- if .Values.application.enabled -}}
{{- with .Values.application }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .appName }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  {{- with .annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app-owner: thiennam23
    {{- with .extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  project: {{ .project }}
  source:
    repoURL: {{ .repo.url }}
    targetRevision: {{ .repo.branch }}
    path: {{ .repo.pathToHelm }}
    {{- if .helm.enabled }}
    helm:
      releaseName: {{ .helm.releaseName }}
      valueFiles: {{ toYaml .helm.valueFiles | nindent 6 }}
      version: v3
    {{- end }}
    directory:
      recurse: {{ .enabledRecurse }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}
  syncPolicy:
    {{- if .syncPolicy.auto }}
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    {{- end }}
    syncOptions: {{ toYaml .syncPolicy.options | nindent 4 }}
    {{- with .syncPolicy.retry }}
    retry: {{ toYaml . | nindent 6 }}
    {{- end -}}
{{- end -}}
{{- end }}