argocdGitSecret:
  enabled: true
  url: "http://gitlab.galaxy.dev/devops/argocd.git"
  username: "administrator"
  token: "<your-gitlab-access-token>"
  type: git

argo-cd:
  configs:
    cm:
      exec.enabled: true
      timeout.reconciliation: 180s
    params:
      controller.repo.server.timeout.seconds: 180
    secret:
      gitlabSecret: <your-random-secret>
  server:
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      ingressClassName: nginx
      hosts:
        - argocd.galaxy.dev
      https: true

argocd-apps:
  applications:
  - name: argocd
    namespace: argocd
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    source:
      helm:
        version: v3
        valueFiles:
          - values.yaml
      path: argocd-install
      repoURL: http://gitlab.galaxy.dev/devops/argocd.git
      targetRevision: HEAD
    syncPolicy:
      syncOptions:
      - CreateNamespace=true
    ignoreDifferences:
    - kind: Secret
      name: argocd-repo-creds
      jqPathExpressions:
      - .data.password
      - .data.username
  - name: argocd-apps
    namespace: argocd
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    source:
      path: argocd-apps/app-of-apps
      repoURL: http://gitlab.galaxy.dev/devops/argocd.git
      targetRevision: HEAD
      directory:
        recurse: true
        jsonnet: {}
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
  - name: argocd-appprojects
    namespace: argocd
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: argocd
    source:
      path: argocd-appprojects
      repoURL: http://gitlab.galaxy.dev/devops/argocd.git
      targetRevision: HEAD
      directory:
        recurse: true
        jsonnet: {}
    syncPolicy:
      automated:
        selfHeal: true
        prune: true

  projects:
  - name: argocd
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    description: Argocd Project
    sourceRepos:
    - '*'
    destinations:
    - namespace: "*"
      server: "*"
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    orphanedResources:
      warn: false
