# -*- mode: ruby -*-
# vi: set ft=ruby :

hostname = ["master", "worker1", "worker2"]

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-22.04"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = "2"
    vb.linked_clone = true
  end

  config.vm.define hostname[0] do |master|
    master.vm.hostname = hostname[0]
    master.vm.network "private_network", ip: "192.168.57.100"
  end

  hostname[1..-1].each_with_index do |node, index|
    config.vm.define node do |worker|
      worker.vm.hostname = node
      worker.vm.network "private_network", ip: "192.168.57.10#{index+1}"
    end
  end

end
