---
- name: Add user, group and ssh key for all node
  hosts: all
  become: true
  vars:
    ansible_user: "vagrant"
    ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
  roles:
    - add-ssh-user

- name: Add host entries
  hosts: all
  become: true
  vars:
    ansible_user: "thiennam23"
    ansible_ssh_private_key_file: "{{ private_key | default('~/.ssh/id_rsa', true) }}"
  tasks:
    - name: Add host entries
      include_tasks: roles/general/tasks/modify_host.yaml
      loop: "{{ host_entries }}"

- name: Install Gitlab
  hosts: gitlab
  become: true
  vars:
    ansible_user: "thiennam23"
    ansible_ssh_private_key_file: "{{ private_key | default('~/.ssh/id_rsa', true) }}"
  roles:
    - gitlab

- name: Install RKE2
  hosts: all
  become: true
  vars:
    ansible_user: "thiennam23"
    ansible_ssh_private_key_file: "{{ private_key | default('~/.ssh/id_rsa', true) }}"
  roles:
    - rke2
