---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: galaxy-landing-dev=registry.gitlab.com/cyanwind23/galaxy-landing
    argocd-image-updater.argoproj.io/write-back-method: git:repocreds
    argocd-image-updater.argoproj.io/galaxy-landing-dev.update-strategy: name
    argocd-image-updater.argoproj.io/galaxy-landing-dev.allow-tags: regexp:^dev-[0-9]{14}-[0-9a-zA-Z]+$
    argocd-image-updater.argoproj.io/galaxy-landing-dev.helm.image-name: polylite.image.repository
    argocd-image-updater.argoproj.io/galaxy-landing-dev.helm.image-tag: polylite.image.tag
    argocd-image-updater.argoproj.io/galaxy-landing-dev.pull-secret: pullsecret:argocd/regcreds-galaxy-landing
  name: galaxy-landing-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: galaxy-landing
  source:
    repoURL: http://gitlab.galaxy.dev/devops/argocd.git
    targetRevision: main
    path: manifest/galaxy-landing
    helm:
      releaseName: galaxy-landing-dev
      valueFiles: 
      - values-dev.yaml
      version: v3
  destination:
    server: https://kubernetes.default.svc
    namespace: galaxy-landing-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
    - CreateNamespace=true
