# -*- mode: ruby -*-
# vi: set ft=ruby :

hostname = ["master", "worker-1", "worker-2"]

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-22.04"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
    vb.cpus = "3"
    vb.linked_clone = true
  end

  hostname.each_with_index do |node, index|
    config.vm.define node do |host|
      host.vm.hostname = node
      host.vm.network "private_network", ip: "192.168.57.10#{index}"
    end
  end

end
